# Generated by Django 5.0.6 on 2024-06-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=30)),
                ('text', models.TextField(default='testimony')),
                ('image', models.ImageField(upload_to='profile_img')),
            ],
        ),
    ]
