# Generated by Django 5.0.6 on 2024-06-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
